### ISSUE TITLE
i want to add function that call next slide with id..

### ISSUE THREAD

**Issue by jaykhatri90165** [dirkgroenen/simple-jQuery-slider#13]
Hello sir,

first of all thank you fro great script & easy to undestand,

now i want to know , how can i add function that nextslider call by id

like example i am in first slider & i want to call forth slider.

**Comment by dirkgroenen** [comment]
Yes that's possible. It's explained in the [README](https://github.com/dirkgroenen/simple-jQuery-slider#control-the-slider)

**Comment by jaykhatri90165** [comment]
thank you so much....
