### ISSUE TITLE
Auto advance ?!?

### ISSUE THREAD

**Issue by bellanet** [dirkgroenen/simple-jQuery-slider#14]
Ok, so maybe I'm just being stupid here, but how do I get the slides to advance automatically ?!? 
I've looked thru the doc's and it seems as if advancing automatically is the default, however I noticed the demo site at http://simpleslider.bitlabsbeta.nl/ doesn't auto-advance nor does the demo included in the downloaded zip file..
I've noticed the demo in the zip file I've downloaded is different than the demo you've got posted online, and I don't know if my copy is older or newer than what you've got posted - my demo is at http://riverside.bellanet.com/demo and I'm not finding the file touchSwipe.js file anywhere to download. It's referenced on the second slide of my demo.

Regards,
WJ Gibson

**Comment by dirkgroenen** [comment]
It's the `slideOnInterval` option taking care of that. 

```
slideOnInterval: true, // Slide on interval
interval: 5000, // Interval to slide on if slideOnInterval is enabled
```
