### ISSUE TITLE
Scroll Down

### ISSUE THREAD

**Issue by MarcelVe** [dirkgroenen/simple-jQuery-slider#17]
Hi, can you help me?
In mobile browser, the page don't scroll down.
Thanks.

**Comment by MarcelVe** [comment]
In mobile browser the page cannot be scrolled up to see the rest of the page.
Again. Thanks.

**Comment by dirkgroenen** [comment]
This is unrelated to the plugin and probably something in your own code.

**Comment by MarcelVe** [comment]
No, its not. It happens with your sample.
But thanks a lot for your help.

**Comment by dirkgroenen** [comment]
In the http://simpleslider.bitlabs.nl/ example you mean? That's correct: vertical scrolling is disabled in there.

**Comment by MarcelVe** [comment]
Exactly, how to enable it? Sorry but my english is not so good.
Thank you again.

**Comment by dirkgroenen** [comment]
I would suggest you to play with inner divs and enabling overflow for them. On mobile it will catch all swiping, so to disable that you'll have to fork the repo and make your own changes to it to make it work.

**Comment by MarcelVe** [comment]
I dont know  how to do that.

**Comment by dirkgroenen** [comment]
Then you'll have something to learn over the next few days. ;) I'm not in the position to help everyone with their questions.
