### ISSUE TITLE
Never ending carousel

### ISSUE THREAD

**Issue by madebytim** [dirkgroenen/simple-jQuery-slider#8]
It would be great to have to option to make it cycle endlessly, for example if i click next when it reaches the end of the carousel instead of sliding all the way back first slide just keep sliding in the same direction.

Thanks!
Tim

**Comment by dirkgroenen** [comment]
Will definitely integrate this feature in the next release.

**Comment by dirkgroenen** [comment]
The ```neverending``` option has been integrated in 2.6.0 which I've just released. Please let me know if you find any problems in it!
